# Generated by Django 2.1.1 on 2018-09-28 02:51

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Coordinator',
                'verbose_name_plural': 'Coordinators',
            },
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=256, null=True)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('social_id', models.CharField(blank=True, max_length=256, null=True)),
                ('phone_number_home', models.CharField(blank=True, max_length=256, null=True)),
                ('phone_number_mobile', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Personal information',
                'verbose_name_plural': 'Personal information',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'indexes': [],
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='coordinator',
            name='personal_information',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='foji.PersonalInformation'),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='foji.User'),
        ),
    ]
