# Generated by Django 2.1.1 on 2018-09-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foji', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetworkInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('twitter', models.URLField()),
                ('youtube', models.URLField()),
                ('pinterest', models.URLField()),
                ('vimeo', models.URLField()),
            ],
            options={
                'verbose_name': 'Social Network information',
            },
        ),
    ]
