# Generated by Django 2.1.1 on 2018-09-30 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foji', '0002_socialnetworkinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orchestra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('orchestra_type', models.CharField(blank=True, choices=[('Infantil', 'infantil'), ('Juvenil', 'juvenil'), ('Infantil-Juvenil', 'infantil-juvenil')], max_length=256, null=True)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('website', models.URLField(blank=True, null=True)),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orchestras', to='foji.Coordinator')),
            ],
            options={
                'verbose_name_plural': 'Orchestras',
                'verbose_name': 'Orchestra',
            },
        ),
    ]
