# Generated by Django 2.1.1 on 2018-09-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foji', '0004_auto_20180930_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('social_id', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number_home', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name_plural': 'Institution Institution',
                'verbose_name': 'Institution information',
            },
        ),
    ]
