# Generated by Django 2.1.1 on 2018-09-30 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foji', '0005_institutioninformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orchestra',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orchestras', to='foji.InstitutionInformation'),
        ),
    ]
