# Generated by Django 2.1.1 on 2018-09-30 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foji', '0006_orchestra_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutioninformation',
            name='legal_representation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to='foji.PersonalInformation'),
        ),
    ]
