# Generated by Django 2.1.1 on 2018-10-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foji', '0007_institutioninformation_legal_representation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutioninformation',
            options={'verbose_name': 'Institution information', 'verbose_name_plural': 'Institution information'},
        ),
        migrations.AlterField(
            model_name='orchestra',
            name='orchestra_type',
            field=models.CharField(blank=True, choices=[('infantil', 'Infantil'), ('juvenil', 'Juvenil'), ('infantil-juvenil', 'Infantil-Juvenil')], max_length=256, null=True),
        ),
    ]
