# Generated by Django 2.1.1 on 2018-10-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foji', '0008_auto_20181001_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
