# Generated by Django 2.1.1 on 2018-10-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foji', '0009_auto_20181006_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
