# Generated by Django 2.1.1 on 2018-10-08 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foji', '0011_auto_20181008_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='orchestra',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orchestras', to='foji.Area'),
        ),
        migrations.AddField(
            model_name='orchestra',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
