# Generated by Django 2.1.1 on 2018-10-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foji', '0012_auto_20181008_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='code',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='province',
            name='code',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(max_length=256),
        ),
    ]
