# Generated by Django 2.1.1 on 2018-10-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foji', '0013_auto_20181008_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='orchestra',
            name='city',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
