# Generated by Django 2.1.1 on 2018-10-13 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foji', '0014_orchestra_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_information', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='foji.PersonalInformation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='foji.User')),
            ],
            options={
                'verbose_name_plural': 'Administrators',
                'verbose_name': 'Administrator',
            },
        ),
    ]
