# Generated by Django 2.1.1 on 2018-10-14 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foji', '0016_auto_20181013_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Cast members',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orchestra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foji.Orchestra')),
                ('personal_information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='foji.PersonalInformation')),
            ],
            options={
                'verbose_name_plural': 'Instructors',
                'verbose_name': 'Instructor',
            },
        ),
        migrations.AddField(
            model_name='castmember',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cast_members', to='foji.Instructor'),
        ),
        migrations.AddField(
            model_name='castmember',
            name='orchestra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foji.Orchestra'),
        ),
        migrations.AddField(
            model_name='castmember',
            name='personal_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foji.PersonalInformation'),
        ),
    ]
