# Generated by Django 2.1.1 on 2018-10-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foji', '0018_auto_20181014_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=256, null=True),
        ),
    ]
