# Generated by Django 2.1.1 on 2018-10-15 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foji', '0020_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='orchestra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directors', to='foji.Orchestra'),
        ),
    ]
