# Generated by Django 2.1.1 on 2018-10-28 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foji', '0026_auto_20181028_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('orchestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding', to='foji.Orchestra')),
            ],
        ),
    ]
