# Generated by Django 2.1.1 on 2018-10-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foji', '0027_funding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castmember',
            name='instructor',
        ),
        migrations.AlterField(
            model_name='funding',
            name='value',
            field=models.CharField(max_length=256),
        ),
    ]
