# Generated by Django 2.1.1 on 2018-10-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foji', '0028_auto_20181028_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='students',
            field=models.IntegerField(default=0),
        ),
    ]
