# Generated by Django 2.1.1 on 2018-10-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foji', '0029_instructor_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='students',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
